repository:
  homepage: https://uvr.esm.is
  description: Next Generation file based typed routing for Vue Router
labels:
  - name: ğŸ bug
    color: ee0701
    description: this isn't working as expected
    oldname: bug
  - name: âœ¨ feature request
    color: fbca04
    description: a new feature request
  - name: âš¡ï¸ enhancement
    color: a2eeef
    description: improvement over an existing feature
    oldname: enhancement
  - name: â™¦ï¸ need repro
    color: c9581c
    description: the issue needs a reproduction for further investigation
  - name: has workaround
    color: 2139c4
    description: has a temporary fix to get around the problem
  - name: ğŸ‘ contribution welcome
    color: 0e8a16
    description: others are welcome to implement/fix this
  - name: ğŸ”¹ typescript
    color: 3178c6
    description: issue related to types
  - name: ğŸ’¬ discussion
    color: 4935ad
    description: topic that requires further discussion
  - name: ğŸ“š docs
    color: 8be281
    description: related to documentation
    oldname: documentation
  - name: 1ï¸âƒ£ good first issue
    color: 7057ff
    description: this should be manageable for new-comers
  - name: ğŸ™ help wanted
    color: 008672
    description: help in this issue is welcome
  - name: wontfix
    color: ffffff
    description: this issue won't be fixed
    oldname: wontfix
  - name: ğŸ”„ data-loaders
    color: baffc9
    description: related to Data Loaders
